### ISSUE TITLE
Throw with TypeError instead of Error

### ISSUE THREAD

**Issue by ibc** [gristlabs/ts-interface-checker#21]
Since this lib checks "types" it would make more sense to have `check()` throw `TypeError` instead of a generic `Error.

**Comment by lordazzi** [comment]
Or a new object that extends TypeError, so I can identity when it's an integration error or an internal error

**Comment by dsagal** [comment]
Currently it throws `VError`, which extends from `Error`. You can check against that. I don't mind inheriting from TypeError instead, but there are quite a few kinds of internal bugs that manifest as TypeError. E.g. "Cannot read property 'foo' of null" is a TypeError. So TypeError is not very useful to distinguish validation from internal errors.

**Comment by lordazzi** [comment]
if this thown an error based on a lib class it's exactly what i need.

**Comment by lordazzi** [comment]
It is throwing Error instead VError. I didn't find any configuration to make it throw VError.

![image](https://user-images.githubusercontent.com/4068344/86798540-3f928780-c047-11ea-8b2d-fd7feafefebf.png)

**Comment by lordazzi** [comment]
The library isn't throwing the VError, it is throwing an Error native object

![image](https://user-images.githubusercontent.com/4068344/86802154-18d65000-c04b-11ea-9df8-fb10aacffef8.png)

![image](https://user-images.githubusercontent.com/4068344/86802247-33102e00-c04b-11ea-87cc-3f57775db9c0.png)

But the first line in stack trace send me to the code of VError creation...
![image](https://user-images.githubusercontent.com/4068344/86802447-6bb00780-c04b-11ea-8c90-08e21f9aefb0.png)

This is a bug or am I doing something wrong?

**Comment by dsagal** [comment]
You are right, there is a deeper [issue about extending Error](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work). Could you check if this fixes the issue for you:
https://github.com/gristlabs/ts-interface-checker/pull/27 ?

**Comment by dsagal** [comment]
With v0.1.12, just released, you can import `VError` and check for it using `instanceof`.
