### ISSUE TITLE
Compare performance with other similar libraries in benchmark repo

### ISSUE THREAD

**Issue by alexmojaki** [gristlabs/ts-interface-checker#48]
Might be nice to add this library to https://github.com/moltar/typescript-runtime-type-benchmarks and see how it does.

**Comment by dsagal** [comment]
Good idea, just made a PR there: https://github.com/moltar/typescript-runtime-type-benchmarks/pull/603
(Performance doesn't shine compared to the optimized "outlier" libraries, but is good compared to the rest.)

**Comment by alexmojaki** [comment]
Oh wow, it's really good! Second place without the outliers! Nice work!

I'd like to see what happens after https://github.com/moltar/typescript-runtime-type-benchmarks/pull/613 is merged, but it should still be good.
