### ISSUE TITLE
cannot import interface from different ts file

### ISSUE THREAD

**Issue by testnetprotonmail** [gristlabs/ts-interface-checker#73]
I want to create typeguards for only a specific file, so I import structures into that file, i.e

from bar.d.ts i import 
```
export interface bar {
example: string
}

```
then in types.d.ts I define
```
foo {
test: bar
 } 

```
which will become
```
 export const foo = t.iface([], {
  "test": "bar",
});
```

and not 
```
 export const foo = t.iface([], {
  "test": {example: string},
});
```

loading a checker in web browser will say that bar does not exist. Unknown type bar
I could do all my types in a single file but that will get messy

**Comment by mrsrhn** [comment]
@testnetprotonmail what was the solution? We have the same problem currently

**Comment by dsagal** [comment]
When `ts-interface-builder` processes a file, it only looks at that particular file, so in your example, doesn't know anything about the meaning of `bar`. But as long as you can build the runtime interfaces for both `bar.d.ts` and `types.d.ts`, then you can use them together. E.g. if they are built into `bar-ti.ts` and `types-ti.ts`, then try creating your checkers as follows:

```
import barTI from 'bar-ti';
import typesTI from 'types-ti';
import {createCheckers} from "ts-interface-checker";

const checkers = createCheckers(barTI, typesTI);
```

You can then use `checkers.foo` which will now know about `bar`, and you could also use `checkers.bar` directly.
